### ISSUE TITLE
PHP Fatal error:  Uncaught Error: [] operator

### ISSUE THREAD

**Issue by emailforos** [tobiaskluge/phpsitemapng#5]
Hi.
I know there is no evolution of this very useful php script but I would like to know it is possible for a php programmer to solve.

The log in my hosting shows this:
```
[10-Jun-2021 17:01:31 Europe/Madrid] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php:59
Stack trace:
#0 /usr/home/abcd.com/web/phpsitemapng/inc/functions/functions.inc.php(99): LayoutEngine->addContentFooter('<div align="cen...')
#1 /usr/home/abcd.com/web/phpsitemapng/inc/startup.php(54): init()
#2 /usr/home/abcd.com/web/phpsitemapng/index.php(10): require_once('/usr/home/crovi...')
#3 {main}
  thrown in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php on line 59
[10-Jun-2021 17:01:41 Europe/Madrid] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php on line 156
[10-Jun-2021 17:01:41 Europe/Madrid] PHP Warning:  Invalid argument supplied for foreach() in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php on line 157
[10-Jun-2021 17:02:11 Europe/Madrid] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /usr/home/abcd.com/web/phpsitemapng/inc/classes/Crawler.class.php:340
Stack trace:
#0 /usr/home/abcd.com/web/phpsitemapng/inc/classes/Crawler.class.php(167): Crawler->_handleHeaders(Array)
#1 /usr/home/abcd.com/web/phpsitemapng/inc/classes/Crawler.class.php(67): Crawler->_getFilesForURL('https://www.cro...')
#2 /usr/home/abcd.com/web/phpsitemapng/inc/functions/parsing.inc.php(249): Crawler->start()
#3 /usr/home/abcd.com/web/phpsitemapng/inc/functions/parsing.inc.php(63): runCrawler(Array, Array)
#4 /usr/home/abcd.com/web/phpsitemapng/index.php(26): parseFilesystem()
#5 {main}
  thrown in /usr/home/abcd.com/web/phpsitemapng/inc/classes/Crawler.class.php on line 340
[10-Jun-2021 17:05:31 Europe/Madrid] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php on line 156
[10-Jun-2021 17:05:31 Europe/Madrid] PHP Warning:  Invalid argument supplied for foreach() in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php on line 157
[10-Jun-2021 17:10:30 Europe/Madrid] PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0
[10-Jun-2021 17:10:30 Europe/Madrid] PHP Warning:  Use of undefined constant PSNG_TXTSITEMAP_URL - assumed 'PSNG_TXTSITEMAP_URL' (this will throw an Error in a future version of PHP) in /usr/home/abcd.com/web/phpsitemapng/inc/functions/parsing.inc.php on line 489
[10-Jun-2021 17:10:30 Europe/Madrid] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php on line 156
[10-Jun-2021 17:10:30 Europe/Madrid] PHP Warning:  Invalid argument supplied for foreach() in /usr/home/abcd.com/web/phpsitemapng/inc/classes/LayoutEngine.class.php on line 157

```
Many thanks for your help

**Comment by tc0nn** [comment]
Replace line 59 in file:  inc/classes/LayoutEngine.class.php

array_push($this->content['content_footer'], $tmp);

Final code:
`    function addContentFooter($msg) {
        $tmp = '<div class="content_footer">'.$msg.'</div>'. "\n";
        if ($this->buffering) {
                array_push($this->content['content_footer'], $tmp);
        } else {
                print $tmp;
        }
    }`

**Comment by emailforos** [comment]
Many thanks.

Error Solved

**Comment by tobiaskluge** [comment]
thanks @emailforos  and @tc0nn - should be in master branch and fixed now.
